# This is a basic workflow to automatically build a Svelte app and deploy it to GitHub Pages

name: deploy-gh-pages


on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install and Build
        run: npm install && npm run build

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: JamesIves/github-pages-deploy-action@4.1.5
      - name: Deploy to GitHub Pages
        with:
          branch: gh-pages
          folder: public
